Added boilerplate code for functions

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,11 +1,36 @@
 #!/bin/env bash
 
+function help() {
+    echo "Help!!"
+}
+
+function generate_uuid() {
+    local type="$1"
+    case $type in
+        1)
+        echo "Generating UUID 1"
+        ;;
+        2)
+        echo "Generating UUID 2"
+        ;; 
+        *)
+        echo "Error: Unknown UUID type requested"
+        echo "Try running '$0 -h'"
+        exit 1
+        ;;
+    esac
+}
+
 function main() {
     while [[ $# -gt 0 ]]; do
         case "$1" in
             -h|--help)
-            echo "Help!!!"
+            help
             shift
+            ;;
+            -g|--generate_uuid)
+            generate_uuid "$2"
+            shift 2
             ;;
         *)
             echo "Error: Unknown option '$1'"
@@ -14,7 +39,7 @@ function main() {
             ;;
         esac
     done
-    echo Success
+    help
 }
 
 main $@
